* Mary and Kenneth Keith Kothman are narcissistic, abusive parents

@@html:<div class="timestamp-pull-left">@@
<2025-06-26 Thu>
@@html:</div>@@

Mary Kothman, board member of the Crescendo Academy of
Music, is an abusive and narcisssistic parent to her
disabled offspring.

My older sibling, who was diagnosed with autism at a young
age, has been threatened on multiple occasions by Mary (and
her husband Dr. Kenneth Keith Kothman) with homelessness,
because of her struggling to get and hold down a job. When
she quit a job with unsafe working conditions, where she was
being exposed to microwave radiation used to shape plastic,
Mary demanded that she apologize to that employer for
quitting without notice. Thankfully, I do not think they
still remove the door from her room, like they did when we
were kids.

During Christmas of 2022, us three siblings gathered so that
Mary could take nonconsensual photographs of us. Mary guilt
trips her kids into doing what she wants (some might call
this emotional abuse), and resorts to punishment when that
doesn't work. As Mary and Keith began one of their usual
fights, yelling at each other and their children, my older
sibling went downstairs to hide from them. Instead of trying
to understand why their disabled autistic offspring was
hiding from them, they laughed upon realizing she was
hiding. I would not be surprised if they cannot remember
laughing at this, as they often laugh at things they don't
understand. More recently, she stopped demanding that we
pose for her photos; instead, she started taking them in a
more unconsensual way, by taking photos unannounced and
catching us off guard.

When I moved back in with my parents after being homeless on
and off for four years, after being told by my doctor that I
might be a victim of human trafficking, Mary and Keith
threatened me with homelessness; all the while, they
demanded that I explain why my doctor said I might be a
victim of human trafficking, while accusing me of harassing
them (and pointing my finger) for attempting to hold them
accountable for their behavior. A disabled adult, with no
ability to leave their siutation, who is expected to do work
for the people they are living with, might be considered a
victim of human trafficking. Their home was never a safe
option for me to leave my situation. I decided to move back
in with them in 2023 after spending a month crashing on
couches, as opposed to being put in a men's shelter as a
trans woman. Mary helped me get back to work by purchasing
men's dress clothes for me, and I went back in the closet as
I found employment. Mary was proud of me for getting a job,
and never again mentioned threatening to kick me out.

Mary's husband and previous director of the school of music
at WMU, Dr.  Kenneth Keith Kothman, seems to think that it
is okay to use the N-word in the privacy of their
home. Quoting president Lyndon B. Johnson doesn't make this
a better look, especially as a Texan with the initials
KKK. Keith, I'm sure your sister would pay the $600 dollars
for you to change your name, if you were serious about
changing it. For those reading, Keith's only sibling was
also given the initials KKK, but she had the wherewithall to
change it.

When I moved out of my parents most recently, I did so in
the middle of the night, so that I would not have to share
my address with my parents or be made to feel bad for not
sharing this information. I made it undeniably clear to both
Mary and Keith that they were *not* to contact me, and I
blocked their phone numbers. Keith showed up at my work,
completely ignoring this boundary; he thought he was being
nice by keeping me on their car insurance, and wanted to let
me know that I still had belongings at their
house. Unfortunately, this was not the first time my parents
have shown up unannounced at my work, and not the first time
one of them has shown up in person while I was no-contact
with them. I again communicated to both Mary and Keith that
they were not to contact me. Keith again violated this
boundary by emailing me, referring to himself as "dad" after
I told him he is not my dad, simply to pester me once more
about my being on their car insurance plan and how they had
been charged for my insurance. Mind you, this is for a car
that I was pressured into buying, even though my family
already has three cars and lives in a home valued around
$500,000. When I told Keith exactly how it made me feel,
having him repeatedly cross my clearly stated boundaries, he
decided to retaliate by also cancelling my AT&T phone plan,
something he never mentioned doing. I did not expect to be
kept on their phone plan, but it's quite telling that they
are punitive when their feelings are hurt. I am certain that
Mary was fully aware of what Keith was doing and saying to
me, as she is party to conversations involving decisions
like these.

When I came out to Mary and Keith in 2017 as a transgender
woman, I told Keith only, and asked that he inform Mary; I
knew Mary would not respond positively. Growing up, she and
Keith made sure I knew that everyone in middle school would
think I'm gay if I chose to play the flute. At 16, I was
finally allowed to pierce my left earlobe - not the right
one of course, because only gay people get their right
earlobe pierced. I learned from Mary and Keith at an early
age that being gay was not okay (despite their having gay
friends), that I would be treated poorly for being gay, and
that they would not stand up for me if I was being bullied
or harassed, especially for my perceived sexuality. Fast
forward back to Christmas of 2017, where my parents
"requested" that I join them in the basement of our family's
residence in Buckhead, Georgia, so that Mary could ask me
her burning questions. I got male clothes for Christmas
again that year, after Mary asked me, "Why can't you just be
metrosexual?", and "Are you going to get the surgery?". She
has never apologized or taken accountability for this, let
alone for the horrific emotional abuse myself and my
siblings endured growing up in her authoritarian,
household. Although Mary has seemingly come to accept my
being a trans woman, she hardly seems proud or happy about
it, looking uncomfortable or outright denying my experiences
when I talk about them. She publicly outs me as trans to
anyone who will listen. At least Mary never said to my face
that I looked like a "street urchin", like she told my
younger sister the first time she dyed her hair with a
streak of red as a child.

The first time I tried to kill myself as a kid, in 2013, I
took a large handful of tylenol and benadryl. The morning
after, Mary forced me to go to school despite my being
physically ill, not having slept at all the night before,
and telling here I did not feel well. When I got to my first
period Chemistry class, I promptly threw up in the trash
can, and a school nurse allowed me to go home and rest.

Mary and Keith, unbeknownst to me, switched me to a
different school where I had no friends for my Junior year
of high school, because they thought it would be a good
change for me and my mental health. They did not ask me if I
wanted this, and instead opted to simply inform me of the
change once it was finalized.

Most of the other times I tried to kill myself were in 2014,
after I had dropped out of college. Mary and Keith made it
clear that not being in school was not a choice, and made
sure I knew how I was letting them down and costing them
money (they had taken out loans to help me go to college). I
cannot count the number of times I tried to hang myself, but
thankfully, it was much more difficult than I had hoped. My
childhood friend, Vincent, unfortunately did not make it out
alive; as far as I'm aware, he killed himself in 2017 - his
parents were incredibly more strict than Mary and
Keith. Vincent and I often talked about running away as
kids, but he was much more serious than I. Mary did not tell
me about the funeral until after it took place.

Growing up, I was not generally allowed to have negative
emotions. After elementary school, Mary and Keith started
ignoring me if I cried. If I raised my voice, spoke with the
incorrect tone, pointed a finger, did not do exactly what
they asked, or otherwise made them displeased, I would
receive verbal abuse, generally from Keith. I learned that
there was nothing I could do or say to stop the yelling, and
that I had best shut my mouth and speak only when allowed to
do so. I learned to disassociate completely from my
emotions, to the point where I was unable to feel them in my
own body, because I had to be completely calm if anyone else
was angry. At 30 years old, I am starting to learn how to
regulate my emotions, take accountability for the harm I
cause, and learn how to live a happy, healthy, and
fulfilling life. You likely won't see this abusive side of
Mary and Keith, because they do a fantastic job of hiding it
from the public.

Mary, and Keith: I know you can do better. Doing better
starts with taking accountability for the impact of your
actions and changing your behavior. This is, in no way, an
invitation to contact me. You will never again be Mom or Dad
to me, but perhaps we can still learn to be friends before
the two of you pass away in your old age. If not, then I
have made my peace.

Congratulations on being elected to the board of the
Crescendo Academy of Music. If you are thinking about taking
me to court for outing you as narcissistic and abusive,
please understand that the bar for defemation is much higher
for public figures such as yourself and Keith, who are
well-known to musicians in Kalamazoo and across the US, and
that you would have to prove "actual malice".
