#+SETUPFILE: ../../html.setup
#+HTML_HEAD_EXTRA: <style>#nav-blog a::after { width: 100% !important; }</style>
#+DATE: <2024-11-18 Mon>

* How I made this website <2024-11-18 Mon>
** Welcome to my inaugural blog post!
****** If you're reading this, you've successfully located my website...

Because we live in a world where capitalism rules every moment of our waking
lives, it's advantageous for me to blog about my adventures in programming, so
that anyone with an inclination to interview or hire me might better understand
my dedication to the craft.

Here's a blog post about how I made the website you're currently viewing, using
two ancient and obscure tools you've likely never heard of: Emacs and
Org-Mode. If you don't know what these are, don't worry, because that's what
I'll be covering first.

** Emacs
What the hell is Emacs, anyway? I know I'm throwing some unfamiliar terminology
at you, but bear with me.

** Org-Mode
If, for whatever reason, you thought Org-Mode would be some newfangled
technology, think again!

Org-Mode, or Organizational Mode, is a mode in Emacs for creating helpful
documents. Each page on this website has its own individual file (ending with a
.org extension).

Org-Mode provides an interesting feature for converting these
org files into HTML ones. HTML files simply define the structure of a page,
including all of the information you're viewing, like this text here!



** Breaking down the site...
